name: Pull Request Tests
on:
  pull_request:
    branches: ['main']
    types: [assigned, opened, synchronize, reopened, labeled]
env:
  app: Accept:application/vnd.github.v3+json

jobs:
  repocheck:
    name: Check if repos are up to date
    runs-on: ubuntu-latest

    outputs:
      current: ${{ steps.check.outputs.current }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check if PR is up to date
      run: |
        #pr_commit=$(git log -1 --format='%H')
        #echo "pr_commit: $pr_commit"
        #pr_target=$(git log remotes/origin/main -1 --format='%H')
        #echo "pr_target: $pr_target"
        #if git merge-base --is-ancestor ${pr_target} ${pr_commit}; then
        if git merge-base --is-ancestor remotes/origin/main @; then
          echo "This pull request is up to date with the base branch."
        else
          echo "This pull request is not up to date with the base branch. Please sync it up."
          exit 1
        fi
