name: Pull Request Check
on:
  pull_request:
    branches: [main]
    types: [assigned, opened, synchronize, reopened, labeled]
env:
  app: Accept:application/vnd.github.v3+json

jobs:
  pull_request_check:
    name: Check if the pull request is up to date
    runs-on: ubuntu-latest

    outputs:
      current: ${{ steps.check.outputs.current }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check if the pull request is up to date
      run: |
        if git merge-base --is-ancestor remotes/origin/main @; then
          echo "This pull request is up to date with the base branch."
        else
          echo "This pull request is not up to date with the base branch. Please sync it up."
          exit 1
        fi
