name: Pull Request Tests
on:
  pull_request:
    branches: ['main']
    types: ['labeled']
env:
  app: Accept:application/vnd.github.v3+json

jobs:
  repocheck:
    name: Check if repos are up to date
    runs-on: ubuntu-latest

    outputs:
      current: ${{ steps.check.outputs.current }}

    steps:
    - uses: actions/checkout@v2

    - name: Wait for caching source
      run: sleep 30

    - name: Check if PR is up to date
      run: |
        pr_commit=$(git log -1 --format='%H')
        pr_target=$(git log remotes/origin/main -1 --format='%H')
        echo "pr_commit: $pr_commit"
        echo "pr_target: $pr_target"
        if [[ git merge-base --is-ancestor remotes/origin/main ${pr_commit} ]]; then
          echo "This pull request is up to date with the target branch."
          exit 0
        else
          echo "This pull request is not up to date with the target branch. Please sync it up."
          exit 1        
        fi
