name: Pull Request Tests
on:
  pull_request:
    branches: ['main']
    types: ['labeled']
env:
  app: Accept:application/vnd.github.v3+json

jobs:
  repocheck:
    name: Check if repos are up to date
    runs-on: ubuntu-latest

    outputs:
      current: ${{ steps.check.outputs.current }}

    steps:
    - uses: actions/checkout@v2

    - name: Check if PR is up to date
      run: |
        git remote -vv
        pr_commit=$(git log -1 --format='%H')
        echo "pr_commit: $pr_commit"
        git fetch
        git branch -vva
        pr_target=$(git log remotes/origin/main -1 --format='%H')
        echo "pr_target: $pr_target"
        git rev-list $pr_commit
        git log -20 --format='%H'
        git merge-base --is-ancestor ${pr_target} ${pr_commit}
        echo $?
        if git merge-base --is-ancestor remotes/origin/main ${pr_commit}; then
          echo "This pull request is up to date with the target branch."
          exit 0
        else
          echo "This pull request is not up to date with the target branch. Please sync it up."
          exit 1
        fi
