name: Pull Request Tests
on:
  pull_request:
    branches: ['main']
    types: ['labeled']
env:
  app: Accept:application/vnd.github.v3+json

jobs:
  repocheck:
    name: Check if repos are up to date
    runs-on: ubuntu-latest

    outputs:
      current: ${{ steps.check.outputs.current }}

    steps:
    - uses: actions/checkout@v2

    - name: Wait for caching source
      run: sleep 10

    - name: Check if PR is up to date
      run: |
        git remote -vv
        git fetch
        git branch -vva
        pr_commit=$(git log -1 --format='%H')
        echo "pr_commit: $pr_commit"
        pr_target=$(git log remotes/origin/develop -1 --format='%H')
        echo "pr_target: $pr_target"
        echo 'before git merge-base'
        echo "git merge-base --is-ancestor ${pr_target} ${pr_commit}"
        if git merge-base --is-ancestor remotes/origin/develop @; then
          echo "This pull request is up to date with the target branch."
        else
          echo "This pull request is not up to date with the target branch. Please sync it up."
          exit 1
        fi
